services:
  db_movie:
    image: postgres
    container_name: db_movie
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg_movie:/var/lib/postgresql/data

  node_app_movie:
    container_name: node_app_movie
    build: .
    ports:
      - 80:3000
    depends_on:
      - db_movie
    env_file:
      - .env

volumes:
  pg_movie: